extends Node
#TODO: adjust and check
var patients = {
	1: {"point_achieved": 0, # for level select?
		"level_image_path": "res://sprites/characters/seamstress.png",
		"precutsceneKey": "precutsceneL1",
		"postcutsceneKey": "postcutsceneL1",
		"questionsSetKey": "questionSetL1",
		"questionSetScript": "res://scripts/dialogue/questionSet1.dialogue",
		"cutscenescript": "res://scripts/dialogue/prologue1.dialogue",
		"name": "Helena",
		"age": 29,
		"occupation": "Seamstress",
		"illness": "Constipation",
		"correctdiagnosistext": "Yaay Helena lived",
		"wrongdiagnosistext": "Helena died oof...",
		"image_path": "res://sprites/characters/seamstress.png",
		"sitting_sprite" : "res://sprites/characters/seamstress_sitting.png",
		"temperature": "39.8",
		"heartrate": "75",
		"breathing": "16",
		"blood_pressure": "120/80",
		"revealed_info": [],
		"revealed_vitals": {},
		"history": "Helena described that she's been having bad headaches.", #make this a array?
		"point_margins": [30,90,150],
		"point_eval":  {
			"You checked blood pressure.": 17,
			"You checked temperature.": 6,
			"You checked breathing.": 13,
			"You asked Tell me more about your fatigue.": 10,
			"You asked Have you been feeling feverish?": 3,
			"You asked Have you experienced a sore throat or cough?": 19,
			"You asked What did you eat today?": 8,
			"You asked Tell me more about your headaches.": 14,
			"You asked How long have you been feeling dizzy?": 2,
			"You asked Have you noticed any changes in your heart rate?": 11,
			"You asked Do you feel short of breath?": 16,
			"You asked How much sleep are you getting?": 5,
			"You asked Have you noticed any changes in your menstrual cycle?": 20,
			"You asked Do you feel like you’re getting enough rest, even if it's just short breaks?": 9
		}
	},
	2: {"point_achieved": 0, # for level select?
		"level_image_path": "res://sprites/characters/husband.png",
		"precutsceneKey": "precutsceneLevel2",
		"postcutsceneKey": "postcutsceneLevel2",
		"questionsSetKey": "questionSetL1",
		"questionSetScript": "res://scripts/dialogue/questionSet1.dialogue",
		"cutscenescript": "res://sprites/prologue1.dialogue",
		"name": "Jonathan",
		"age": 41,
		"occupation": "Carpenter",
		"illness": "Constipation",
		"correctdiagnosistext": "Yaay Helena lived",
		"wrongdiagnosistext": "Helena died oof...",
		"image_path": "res://sprites/characters/husband.png",
		"sitting_sprite" : "res://sprites/characters/husband.png",
		"temperature": "36.8",
		"heartrate": "75",
		"breathing": "16",
		"revealed_info": [],
		"revealed_vitals": {},
		"history": "Jonathan mentions frequent dizziness after working in the sun.",
		"point_margins": [100,200,300],
		"point_eval":  {
			"You checked blood pressure.": 17,
			"You checked temperature.": 6,
			"You checked breathing.": 13,
			"You asked Tell me more about your fatigue.": 10,
			"You asked Have you been feeling feverish?": 3,
			"You asked Have you experienced a sore throat or cough?": 19,
			"You asked What did you eat today?": 8,
			"You asked Tell me more about your headaches.": 14,
			"You asked How long have you been feeling dizzy?": 2,
			"You asked Have you noticed any changes in your heart rate?": 11,
			"You asked Do you feel short of breath?": 16,
			"You asked How much sleep are you getting?": 5,
			"You asked Have you noticed any changes in your menstrual cycle?": 20,
			"You asked Do you feel like you’re getting enough rest, even if it's just short breaks?": 9
		}
	},
	"More": {
		"level_image_path": "res://sprites/characters/witch_cool.png",
		"name": "Comming Soon!",
	}
}
